apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openbeats.fullname" . }}-audio
  labels:
    {{- include "openbeats.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
  {{- end }}
