// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: favorites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO favorites (user_id, track_id)
VALUES ($1, $2)
ON CONFLICT (user_id, track_id) DO NOTHING
`

type AddFavoriteParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	TrackID pgtype.UUID `json:"track_id"`
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.UserID, arg.TrackID)
	return err
}

const listFavoriteTracks = `-- name: ListFavoriteTracks :many
SELECT t.id, t.title, t.artist, t.album, t.duration_seconds, t.file_path, t.mime_type, t.cover_path, t.uploaded_by, t.created_at FROM favorites f
JOIN tracks t ON t.id = f.track_id
WHERE f.user_id = $1
ORDER BY f.created_at DESC
`

func (q *Queries) ListFavoriteTracks(ctx context.Context, userID pgtype.UUID) ([]Track, error) {
	rows, err := q.db.Query(ctx, listFavoriteTracks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Track{}
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.DurationSeconds,
			&i.FilePath,
			&i.MimeType,
			&i.CoverPath,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM favorites WHERE user_id = $1 AND track_id = $2
`

type RemoveFavoriteParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	TrackID pgtype.UUID `json:"track_id"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.UserID, arg.TrackID)
	return err
}
