// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Playlist struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PlaylistTrack struct {
	PlaylistID pgtype.UUID `json:"playlist_id"`
	TrackID    pgtype.UUID `json:"track_id"`
	Position   int32       `json:"position"`
}

type Track struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	Artist          string             `json:"artist"`
	Album           string             `json:"album"`
	DurationSeconds int32              `json:"duration_seconds"`
	FilePath        string             `json:"file_path"`
	MimeType        string             `json:"mime_type"`
	CoverPath       pgtype.Text        `json:"cover_path"`
	UploadedBy      pgtype.UUID        `json:"uploaded_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
