// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: playlists.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPlaylistTrack = `-- name: AddPlaylistTrack :one
INSERT INTO playlist_tracks (playlist_id, track_id, position)
VALUES ($1, $2, $3)
ON CONFLICT (playlist_id, track_id) DO UPDATE SET position = EXCLUDED.position
RETURNING playlist_id, track_id, position
`

type AddPlaylistTrackParams struct {
	PlaylistID pgtype.UUID `json:"playlist_id"`
	TrackID    pgtype.UUID `json:"track_id"`
	Position   int32       `json:"position"`
}

func (q *Queries) AddPlaylistTrack(ctx context.Context, arg AddPlaylistTrackParams) (PlaylistTrack, error) {
	row := q.db.QueryRow(ctx, addPlaylistTrack, arg.PlaylistID, arg.TrackID, arg.Position)
	var i PlaylistTrack
	err := row.Scan(&i.PlaylistID, &i.TrackID, &i.Position)
	return i, err
}

const createPlaylist = `-- name: CreatePlaylist :one
INSERT INTO playlists (name, owner_id)
VALUES ($1, $2)
RETURNING id, name, owner_id, created_at
`

type CreatePlaylistParams struct {
	Name    string      `json:"name"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error) {
	row := q.db.QueryRow(ctx, createPlaylist, arg.Name, arg.OwnerID)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const getPlaylist = `-- name: GetPlaylist :one
SELECT id, name, owner_id, created_at FROM playlists WHERE id = $1
`

func (q *Queries) GetPlaylist(ctx context.Context, id pgtype.UUID) (Playlist, error) {
	row := q.db.QueryRow(ctx, getPlaylist, id)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const listPlaylistTracks = `-- name: ListPlaylistTracks :many
SELECT t.id, t.title, t.artist, t.album, t.duration_seconds, t.file_path, t.mime_type, t.cover_path, t.uploaded_by, t.created_at, pt.position
FROM playlist_tracks pt
JOIN tracks t ON t.id = pt.track_id
WHERE pt.playlist_id = $1
ORDER BY pt.position
`

type ListPlaylistTracksRow struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	Artist          string             `json:"artist"`
	Album           string             `json:"album"`
	DurationSeconds int32              `json:"duration_seconds"`
	FilePath        string             `json:"file_path"`
	MimeType        string             `json:"mime_type"`
	CoverPath       pgtype.Text        `json:"cover_path"`
	UploadedBy      pgtype.UUID        `json:"uploaded_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Position        int32              `json:"position"`
}

func (q *Queries) ListPlaylistTracks(ctx context.Context, playlistID pgtype.UUID) ([]ListPlaylistTracksRow, error) {
	rows, err := q.db.Query(ctx, listPlaylistTracks, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaylistTracksRow{}
	for rows.Next() {
		var i ListPlaylistTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.DurationSeconds,
			&i.FilePath,
			&i.MimeType,
			&i.CoverPath,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistsByOwner = `-- name: ListPlaylistsByOwner :many
SELECT id, name, owner_id, created_at FROM playlists WHERE owner_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPlaylistsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Playlist, error) {
	rows, err := q.db.Query(ctx, listPlaylistsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Playlist{}
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextPlaylistPosition = `-- name: NextPlaylistPosition :one
SELECT COALESCE(MAX(position), 0) + 1 AS next_position
FROM playlist_tracks
WHERE playlist_id = $1
`

func (q *Queries) NextPlaylistPosition(ctx context.Context, playlistID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextPlaylistPosition, playlistID)
	var next_position int32
	err := row.Scan(&next_position)
	return next_position, err
}
