// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddFavorite(ctx context.Context, arg AddFavoriteParams) error
	AddPlaylistTrack(ctx context.Context, arg AddPlaylistTrackParams) (PlaylistTrack, error)
	CountUsers(ctx context.Context) (int64, error)
	CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error)
	CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTrack(ctx context.Context, id pgtype.UUID) error
	GetPlaylist(ctx context.Context, id pgtype.UUID) (Playlist, error)
	GetTrack(ctx context.Context, id pgtype.UUID) (Track, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListFavoriteTracks(ctx context.Context, userID pgtype.UUID) ([]Track, error)
	ListPlaylistTracks(ctx context.Context, playlistID pgtype.UUID) ([]ListPlaylistTracksRow, error)
	ListPlaylistsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Playlist, error)
	ListTracks(ctx context.Context, arg ListTracksParams) ([]Track, error)
	ListUsers(ctx context.Context) ([]User, error)
	NextPlaylistPosition(ctx context.Context, playlistID pgtype.UUID) (int32, error)
}

var _ Querier = (*Queries)(nil)
