// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tracks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrack = `-- name: CreateTrack :one
INSERT INTO tracks (title, artist, album, duration_seconds, file_path, mime_type, cover_path, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, title, artist, album, duration_seconds, file_path, mime_type, cover_path, uploaded_by, created_at
`

type CreateTrackParams struct {
	Title           string      `json:"title"`
	Artist          string      `json:"artist"`
	Album           string      `json:"album"`
	DurationSeconds int32       `json:"duration_seconds"`
	FilePath        string      `json:"file_path"`
	MimeType        string      `json:"mime_type"`
	CoverPath       pgtype.Text `json:"cover_path"`
	UploadedBy      pgtype.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error) {
	row := q.db.QueryRow(ctx, createTrack,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.DurationSeconds,
		arg.FilePath,
		arg.MimeType,
		arg.CoverPath,
		arg.UploadedBy,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artist,
		&i.Album,
		&i.DurationSeconds,
		&i.FilePath,
		&i.MimeType,
		&i.CoverPath,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTrack = `-- name: DeleteTrack :exec
DELETE FROM tracks WHERE id = $1
`

func (q *Queries) DeleteTrack(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTrack, id)
	return err
}

const getTrack = `-- name: GetTrack :one
SELECT id, title, artist, album, duration_seconds, file_path, mime_type, cover_path, uploaded_by, created_at FROM tracks WHERE id = $1
`

func (q *Queries) GetTrack(ctx context.Context, id pgtype.UUID) (Track, error) {
	row := q.db.QueryRow(ctx, getTrack, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artist,
		&i.Album,
		&i.DurationSeconds,
		&i.FilePath,
		&i.MimeType,
		&i.CoverPath,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listTracks = `-- name: ListTracks :many
SELECT id, title, artist, album, duration_seconds, file_path, mime_type, cover_path, uploaded_by, created_at FROM tracks
WHERE ($1::text IS NULL OR artist ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL OR album ILIKE '%' || $2::text || '%')
  AND (
        $3::text IS NULL
        OR title ILIKE '%' || $3::text || '%'
        OR artist ILIKE '%' || $3::text || '%'
        OR album ILIKE '%' || $3::text || '%'
      )
ORDER BY created_at DESC
`

type ListTracksParams struct {
	Artist pgtype.Text `json:"artist"`
	Album  pgtype.Text `json:"album"`
	Q      pgtype.Text `json:"q"`
}

func (q *Queries) ListTracks(ctx context.Context, arg ListTracksParams) ([]Track, error) {
	rows, err := q.db.Query(ctx, listTracks, arg.Artist, arg.Album, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Track{}
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.DurationSeconds,
			&i.FilePath,
			&i.MimeType,
			&i.CoverPath,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
